POST localhost:8081/db/seats/change
Content-Type: application/json

{
  "seat_code": "1JA1"
}


###
POST localhost:8082/db/recommendation
Content-Type: application/json

{
    "userid": "2017037039",
    "isPreference": 1,
    "person": 2,
    "isEdge": 1
}
